<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=Edge;chrome=1">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
		<link rel="icon" type="image/png" href="img/common/favicon.png">
		<meta property="og:title" content="Wanderlust 2">
		<meta property="og:type" content="website">
		<meta property="og:site_name" content="Wanderlust 2">
		<meta property="og:description" content="Play Wanderlust 2, an HTML5 RPG deisgned for your browsers!">

		<link rel="stylesheet" type="text/css" media="screen, projection" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/css/bootstrap.min.css" />
		<link rel="stylesheet" type="text/css" media="screen, projection" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css" />
		<link rel="stylesheet" type="text/css" media="screen, projection" href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.0/animate.min.css" />
		<link rel="stylesheet" type="text/css" media="screen, projection" href="css/marka.min.css" />
		<link rel="stylesheet" type="text/css" media="screen, projection" href="css/style.min.css" />
		<link rel="stylesheet" type="text/css" media="screen, projection" href="css/sprites.min.css" />

		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="js/marka.min.js"></script>
	</head>
